apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: fakod/cnde-example-springboot-crud-mysql-vuejs:latest
    imagePullPolicy: IfNotPresent
